---
title: "Lab 11"
author: Junseo Choi
date: "`r Sys.Date()`"
documentclass: article
geometry: margin=1in
fontsize: 11pt
output: flexdashboard::flex_dashboard
---

```{r setup, include = FALSE}
library(tidyverse)
library(plotly)
library(crosstalk)

pokemon <- read_csv("pokemon.csv")
shared_pokemon <- SharedData$new(pokemon)
```

SidebarName {.sidebar}
----------------------
```{r}
filter_select("poke_type", "Pokemon Type", shared_pokemon, ~`Type 1`)
```


Column 1
-------------------------------------

### Distribution of Stat by Pokemon Type

```{r}
p1 <- shared_pokemon %>%
  ggplot(aes(x = reorder(`Type 1`, Total, FUN = median),
                          y = Total, fill = `Type 1`)) +
  geom_boxplot() +
  labs(x = "Type of Pokemon") + theme(axis.text.x = element_text(angle = 45))

ggplotly(p1)
```

Column 2
-------------------------------------

### Attack vs Defense by Pokemon Type

```{r}
p <- shared_pokemon %>%
  ggplot(aes(x = Defense, y = Attack, color = `Type 1`)) +
  geom_point() +
  labs(title = "Attack vs Defense by Type 1",
       x = "Defense",
       y = "Attack")

ggplotly(p)
```



